// Research snapshot: 2026-09-07. Links are primary sources, not integrations.
export const TOOLS = [
  {
    id: "capcut",
    name: "CapCut",
    kind: "Editor proprietário",
    license: "Termos do fornecedor",
    stage: "Montagem, voz e legendas",
    route:
      "Pacote editorial → edição manual no CapCut → revisão do arquivo exportado.",
    cost: "Recursos e limites dependem do plano, região e versão. Conferir na conta.",
    readiness: "Handoff manual",
    url: "https://www.capcut.com/tools/desktop-ai-power",
    note: "O site oficial documenta Script to Video, Auto Reframe e Auto Captions. O Órbita exporta instruções e SRT de planejamento; não um projeto nativo CapCut.",
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    kind: "Geração proprietária",
    license: "Termos do fornecedor",
    stage: "Planos e inserts gerados",
    route:
      "Storyboard → prompt por cena → geração no site → seleção de takes → editor.",
    cost: "Planos/créditos. Nenhuma gratuidade ilimitada presumida.",
    readiness: "API oficial para fase futura",
    url: "https://docs.higgsfield.ai/docs",
    note: "A API oficial tem autenticação e tarefas assíncronas. Não está conectada ao Órbita. A plataforma não é open source.",
    source:
      "https://higgsfield.ai/creator-hub/help-center/getting-started/official-higgsfield-platforms",
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    kind: "Código aberto",
    license: "GPL-3.0; modelos têm licenças próprias",
    stage: "Workflows visuais",
    route:
      "Cena → workflow versionado → execução no PC/servidor → mídia aprovada.",
    cost: "Hardware, modelos e tempo de execução. Código aberto não elimina esses custos.",
    readiness: "Avaliar no PC",
    url: "https://github.com/Comfy-Org/ComfyUI",
    note: "Interface em nós e backend para geração. Plugins, pesos e requisitos de memória precisam ser avaliados por workflow.",
  },
  {
    id: "whisper",
    name: "faster-whisper",
    kind: "Código aberto",
    license: "MIT",
    stage: "Transcrição e base de legendas",
    route: "Áudio final → transcrição → revisão de nomes e tempos → legendas.",
    cost: "Execução local em CPU/GPU compatível; avaliar duração e memória.",
    readiness: "Avaliar no PC",
    url: "https://github.com/SYSTRAN/faster-whisper",
    note: "Transcrição com CTranslate2. A revisão humana continua necessária para texto e sincronização.",
  },
  {
    id: "ffmpeg",
    name: "FFmpeg",
    kind: "Código aberto",
    license: "LGPL-2.1+; componentes opcionais GPL",
    stage: "Conversão e finalização técnica",
    route: "Arquivo do editor → inspeção, conversão e variantes → revisão.",
    cost: "Processamento e armazenamento locais.",
    readiness: "Adaptador futuro",
    url: "https://ffmpeg.org/",
    source: "https://ffmpeg.org/legal.html",
    note: "Ferramenta para processamento de áudio/vídeo. Registrar versão e opções da compilação antes de integrar.",
  },
  {
    id: "shotcut",
    name: "Shotcut",
    kind: "Código aberto",
    license: "GPL-3.0",
    stage: "Edição no desktop",
    route: "Mídias e roteiro → timeline manual → mixagem → exportação.",
    cost: "Hardware local; sem cobrança de licença do editor.",
    readiness: "Alternativa para o PC",
    url: "https://github.com/mltframework/shotcut",
    note: "Editor multiplataforma baseado em MLT. Opção para um fluxo local; não foi instalado neste dispositivo.",
  },
  {
    id: "opencut",
    name: "OpenCut",
    kind: "Código aberto",
    license: "MIT",
    stage: "Edição e pesquisa de integração",
    route:
      "Avaliar a versão classic e acompanhar a nova arquitetura antes de adotar.",
    cost: "Infraestrutura e processamento dependem da implantação.",
    readiness: "Em avaliação",
    url: "https://github.com/opencut-app/opencut",
    note: "O README informa uma reescrita e recomenda a versão classic para uso atual. Editor API, MCP e headless são itens anunciados para a nova arquitetura, não assumidos como prontos.",
  },
];

const field = (key, label, hint, type = "textarea") => ({
  key,
  label,
  hint,
  type,
});
export const STEPS = [
  {
    id: "brief",
    title: "Direção editorial",
    role: "Direção",
    output: "Briefing de produção",
    icon: "spark",
    fields: [
      field(
        "audience",
        "Público e necessidade",
        "Quem assiste e qual dúvida concreta este vídeo resolve?",
      ),
      field(
        "promise",
        "Promessa verificável",
        "O que a pessoa poderá entender ou fazer ao terminar?",
      ),
      field(
        "angle",
        "Abordagem original",
        "Qual experimento, interpretação ou demonstração é sua?",
      ),
      field("duration", "Duração planejada (segundos)", "Ex.: 90", "number"),
      field(
        "budget",
        "Teto de gasto (R$)",
        "Informe 0 para um fluxo sem serviços pagos.",
        "number",
      ),
    ],
    tasks: [
      "Definir público e problema",
      "Escolher uma promessa observável",
      "Explicitar a contribuição original",
      "Fixar duração e teto de custo",
    ],
    checks: [
      "O público e o resultado estão claros",
      "A promessa pode ser entregue com os recursos disponíveis",
      "A abordagem tem contribuição editorial própria",
    ],
  },
  {
    id: "research",
    title: "Fontes e evidências",
    role: "Pesquisa",
    output: "Dossiê de evidências",
    icon: "search",
    fields: [
      field(
        "claims",
        "Afirmações que o vídeo fará",
        "Liste fatos e associe-os às fontes cadastradas em Evidências.",
      ),
      field(
        "uncertainties",
        "Lacunas e tratamento",
        "O que será verificado, omitido ou apresentado como hipótese? Para ficção, declare o enquadramento.",
      ),
    ],
    tasks: [
      "Cadastrar fonte primária ou registro próprio",
      "Relacionar cada afirmação à evidência",
      "Verificar data e contexto",
      "Resolver lacunas ou delimitar incertezas",
    ],
    checks: [
      "Abri e conferi as fontes citadas",
      "Separei fatos, opiniões e hipóteses",
      "Não restaram afirmações centrais sem sustentação",
    ],
  },
  {
    id: "hook",
    title: "Gancho e promessa",
    role: "Narrativa",
    output: "Abertura escolhida",
    icon: "play",
    fields: [
      field(
        "hookA",
        "Abertura A",
        "Uma pergunta concreta ou resultado que vamos mostrar.",
      ),
      field("hookB", "Abertura B", "Outra abordagem para a mesma promessa."),
      field(
        "hookChoice",
        "Escolha e motivo",
        "Escolha A ou B e explique como o restante do vídeo entrega essa abertura.",
      ),
    ],
    tasks: [
      "Escrever duas aberturas",
      "Definir a primeira prova visual",
      "Escolher a abordagem",
      "Conferir coerência com a promessa",
    ],
    checks: [
      "A abertura não promete além do material",
      "Há uma razão concreta para continuar assistindo",
      "A escolha não depende de engajamento artificial",
    ],
  },
  {
    id: "script",
    title: "Roteiro e narrativa",
    role: "Roteiro",
    output: "Roteiro narrável",
    icon: "edit",
    fields: [
      field(
        "script",
        "Roteiro completo",
        "Abertura, desenvolvimento, demonstração e conclusão. Separe as falas em blocos.",
      ),
      field(
        "payoff",
        "Conclusão e chamada para ação",
        "Como você entrega a promessa? Qual ação faz sentido para este público?",
      ),
    ],
    tasks: [
      "Estruturar começo, desenvolvimento e conclusão",
      "Inserir exemplos e demonstrações",
      "Ler o roteiro em voz alta",
      "Conferir fatos e duração aproximada",
    ],
    checks: [
      "O roteiro entrega a promessa inicial",
      "A leitura cabe no tempo com pausas",
      "O texto tem narrativa e análise próprias",
    ],
  },
  {
    id: "storyboard",
    title: "Cenas e ritmo",
    role: "Direção visual",
    output: "Storyboard com tempos",
    icon: "video",
    fields: [
      field(
        "visualStyle",
        "Direção visual",
        "Paleta, tipografia, enquadramentos e referências. Defina o que deve permanecer consistente.",
      ),
      field(
        "rhythm",
        "Ritmo e transições",
        "Onde mostrar tela, usar insert, dar pausa e trocar o plano?",
      ),
    ],
    tasks: [
      "Dividir o roteiro em cenas",
      "Definir duração e voz por cena",
      "Descrever a função de cada visual",
      "Conferir duração total do storyboard",
    ],
    checks: [
      "Cada cena tem uma função narrativa",
      "As imagens ajudam a entender a informação",
      "A soma das cenas corresponde à duração planejada",
    ],
  },
  {
    id: "assets",
    title: "Mídias e geração",
    role: "Produção visual",
    output: "Lista de mídias rastreáveis",
    icon: "folder",
    fields: [
      field(
        "assetPlan",
        "Plano de produção",
        "Quais cenas usam captura própria, banco ou geração? Indique ferramenta e alternativa.",
      ),
      field(
        "generationRules",
        "Consistência e seleção de takes",
        "Personagens, ambiente, movimento, artefatos a rejeitar e limite de tentativas.",
      ),
    ],
    tasks: [
      "Escolher ferramenta por cena",
      "Produzir ou localizar os arquivos",
      "Registrar origem e permissão de uso",
      "Selecionar takes e registrar gastos",
    ],
    checks: [
      "As mídias selecionadas foram conferidas",
      "Registrei origem e condição de uso",
      "Rejeitei artefatos que distorcem a mensagem",
    ],
  },
  {
    id: "audio",
    title: "Voz e desenho sonoro",
    role: "Áudio",
    output: "Plano de voz e mixagem",
    icon: "pulse",
    fields: [
      field(
        "voicePlan",
        "Voz e pronúncia",
        "Voz própria ou ferramenta; ritmo, nomes e termos técnicos.",
      ),
      field(
        "soundPlan",
        "Trilha, efeitos e mixagem",
        "Origem da trilha, pausas, volume relativo e revisão em alto-falante de celular.",
      ),
    ],
    tasks: [
      "Gravar ou preparar a narração",
      "Revisar pronúncia e pausas",
      "Escolher trilha e efeitos com origem",
      "Conferir inteligibilidade e picos",
    ],
    checks: [
      "A narração é compreensível no celular",
      "A trilha não encobre a voz",
      "A origem de voz, música e efeitos está documentada",
    ],
  },
  {
    id: "edit",
    title: "Montagem no editor",
    role: "Edição",
    output: "Plano de montagem e referência do corte",
    icon: "board",
    fields: [
      field(
        "editor",
        "Editor escolhido",
        "CapCut, Shotcut ou outra ferramenta. Registre versão e ambiente.",
        "input",
      ),
      field(
        "editNotes",
        "Plano de edição",
        "Ordem dos takes, cortes, sobreposições, zooms e pausas. Use o pacote de montagem.",
      ),
      field(
        "cutReference",
        "Referência do corte",
        "Nome do arquivo, versão e localização. Ex.: piloto-v01.mp4, pasta local Edição.",
        "input",
      ),
    ],
    tasks: [
      "Organizar os materiais no editor",
      "Montar o corte segundo o storyboard",
      "Ajustar ritmo, transições e áudio",
      "Registrar a versão do corte exportado",
    ],
    checks: [
      "O corte foi assistido do início ao fim",
      "Os cortes preservam o sentido das falas",
      "A referência aponta para a versão revisada",
    ],
  },
  {
    id: "captions",
    title: "Legendas e acessibilidade",
    role: "Finalização",
    output: "Legendas revisadas",
    icon: "chat",
    fields: [
      field(
        "captionPlan",
        "Revisão de legendas",
        "Ferramenta de transcrição, nomes corrigidos, sincronização e quebra de linhas.",
      ),
      field(
        "accessibility",
        "Leitura no celular",
        "Contraste, tamanho, área livre da interface e informações transmitidas só por imagem.",
      ),
    ],
    tasks: [
      "Transcrever o áudio final",
      "Corrigir nomes e pontuação",
      "Sincronizar e revisar as legendas",
      "Conferir legibilidade no formato final",
    ],
    checks: [
      "As legendas refletem o áudio final",
      "Os tempos foram revisados no vídeo",
      "O texto é legível no celular",
    ],
  },
  {
    id: "package",
    title: "Embalagem por rede",
    role: "Editorial",
    output: "Pacote de distribuição planejado",
    icon: "layers",
    fields: [
      field(
        "titleA",
        "Título A",
        "Promessa clara e sustentada pelo vídeo.",
        "input",
      ),
      field(
        "titleB",
        "Título B",
        "Alternativa para testar uma hipótese.",
        "input",
      ),
      field(
        "description",
        "Descrição e créditos",
        "Contexto, referências e chamada para ação.",
      ),
      field(
        "networkPlan",
        "Adaptação por rede",
        "YouTube, Instagram, TikTok, Facebook ou Kwai: duração, enquadramento, capa e legenda. Verificar especificações antes de publicar.",
      ),
    ],
    tasks: [
      "Preparar títulos e conceito de capa",
      "Escrever descrição e créditos",
      "Planejar variantes por rede",
      "Conferir promessa e enquadramento",
    ],
    checks: [
      "Título e capa correspondem ao vídeo",
      "Créditos e contexto estão completos",
      "As variantes foram planejadas para cada rede escolhida",
    ],
  },
  {
    id: "qa",
    title: "Revisão e entrega",
    role: "Revisão humana",
    output: "Parecer de aprovação editorial",
    icon: "check",
    fields: [
      field(
        "qaNotes",
        "Parecer final",
        "Confirme versão, conteúdo, áudio, imagem, legendas e correções.",
      ),
      field(
        "delivery",
        "Entrega e organização",
        "Onde estão o arquivo final, fontes e materiais? Identifique o responsável pelo próximo passo.",
      ),
    ],
    tasks: [
      "Rever fatos e originalidade",
      "Inspecionar o arquivo final",
      "Comparar custo com orçamento",
      "Aprovar e organizar a entrega",
    ],
    checks: [
      "Assisti ao arquivo final na versão indicada",
      "Resolvi as pendências editoriais e técnicas",
      "A entrega está identificada e o custo cabe no limite",
    ],
  },
  {
    id: "learn",
    title: "Aprendizado e novo ciclo",
    role: "Análise",
    output: "Hipótese para o próximo vídeo",
    icon: "pulse",
    fields: [
      field(
        "observation",
        "O que foi observado?",
        "Use métricas registradas ou feedback de revisão. Se não publicou, deixe isso explícito.",
      ),
      field(
        "nextHypothesis",
        "Hipótese do próximo experimento",
        "Qual única mudança queremos testar e por quê?",
      ),
      field(
        "successMetric",
        "Critério do próximo teste",
        "Qual medida, janela e condição ajudarão a decidir? Não atribua causalidade a uma amostra isolada.",
      ),
    ],
    tasks: [
      "Registrar feedback e sua origem",
      "Separar observação de interpretação",
      "Escolher uma mudança para testar",
      "Criar o briefing do próximo ciclo",
    ],
    checks: [
      "Os resultados têm origem identificada",
      "A hipótese é específica e testável",
      "O próximo ciclo altera uma variável principal",
    ],
  },
];
